export const KANBAN_COLUMNS = [
  { id: "New",          label: "New"          },
  { id: "Assigned",     label: "Assigned"     },
  { id: "In Progress",  label: "In Progress"  },
  { id: "Under Review", label: "Under Review" },
  { id: "Completed",    label: "Completed"    },
];

export const empMockTasks = [
  {
    id: "1",
    task:           "Design product listing page",
    projectName:    "E-Commerce Platform",
    module:         "UI/UX",
    task_assignees: "Sara Ahmed",
    assigneeAvatar: "",
    task_priority:  "High",
    task_start_date:"Jun 01, 2026",
    task_end_date:  "Jun 29, 2026",
    project_status: "In Progress",
    status:         "In Progress",
    comments:       3,
    attachments:    5,
    // kanban aliases
    title:    "Design product listing page",
    priority: "High",
    deadline: "Jun 29, 2026",
    assigneeName: "Sara Ahmed",
    project: "E-Commerce Platform",
  },
  {
    id: "2",
    task:           "Implement payment gateway",
    projectName:    "E-Commerce Platform",
    module:         "Backend",
    task_assignees: "Sara Ahmed",
    assigneeAvatar: "",
    task_priority:  "High",
    task_start_date:"Jun 05, 2026",
    task_end_date:  "Jun 29, 2026",
    project_status: "Under Review",
    status:         "Under Review",
    comments:       2,
    attachments:    3,
    title:    "Implement payment gateway",
    priority: "High",
    deadline: "Jun 29, 2026",
    assigneeName: "Sara Ahmed",
    project: "E-Commerce Platform",
  },
  {
    id: "3",
    task:           "Setup CI/CD pipeline",
    projectName:    "Healthcare Portal",
    module:         "DevOps",
    task_assignees: "Sara Ahmed",
    assigneeAvatar: "",
    task_priority:  "Medium",
    task_start_date:"May 20, 2026",
    task_end_date:  "Jun 29, 2026",
    project_status: "Assigned",
    status:         "Assigned",
    comments:       1,
    attachments:    2,
    title:    "Setup CI/CD pipeline",
    priority: "Medium",
    deadline: "Jun 29, 2026",
    assigneeName: "Sara Ahmed",
    project: "Healthcare Portal",
  },
  {
    id: "4",
    task:           "Patient records API",
    projectName:    "Healthcare Portal",
    module:         "Backend",
    task_assignees: "Sara Ahmed",
    assigneeAvatar: "",
    task_priority:  "High",
    task_start_date:"May 25, 2026",
    task_end_date:  "Jun 29, 2026",
    project_status: "In Progress",
    status:         "In Progress",
    comments:       4,
    attachments:    1,
    title:    "Patient records API",
    priority: "High",
    deadline: "Jun 29, 2026",
    assigneeName: "Sara Ahmed",
    project: "Healthcare Portal",
  },
  {
    id: "5",
    task:           "Design CRM dashboard wireframes",
    projectName:    "CRM Dashboard",
    module:         "UI/UX",
    task_assignees: "Sara Ahmed",
    assigneeAvatar: "",
    task_priority:  "Medium",
    task_start_date:"Jun 01, 2026",
    task_end_date:  "Jun 29, 2026",
    project_status: "New",
    status:         "New",
    comments:       0,
    attachments:    2,
    title:    "Design CRM dashboard wireframes",
    priority: "Medium",
    deadline: "Jun 29, 2026",
    assigneeName: "Sara Ahmed",
    project: "CRM Dashboard",
  },
  {
    id: "6",
    task:           "Write unit tests for auth module",
    projectName:    "Mobile Banking App",
    module:         "QA",
    task_assignees: "Sara Ahmed",
    assigneeAvatar: "",
    task_priority:  "Medium",
    task_start_date:"May 15, 2026",
    task_end_date:  "Jun 29, 2026",
    project_status: "In Progress",
    status:         "In Progress",
    comments:       2,
    attachments:    0,
    title:    "Write unit tests for auth module",
    priority: "Medium",
    deadline: "Jun 29, 2026",
    assigneeName: "Sara Ahmed",
    project: "Mobile Banking App",
  },
  {
    id: "7",
    task:           "Optimize database queries",
    projectName:    "Mobile Banking App",
    module:         "Backend",
    task_assignees: "Sara Ahmed",
    assigneeAvatar: "",
    task_priority:  "High",
    task_start_date:"Apr 20, 2026",
    task_end_date:  "Jun 29, 2026",
    project_status: "Completed",
    status:         "Completed",
    comments:       1,
    attachments:    3,
    title:    "Optimize database queries",
    priority: "High",
    deadline: "Jun 29, 2026",
    assigneeName: "Sara Ahmed",
    project: "Mobile Banking App",
  },
  {
    id: "8",
    task:           "Build notification system",
    projectName:    "Mobile Banking App",
    module:         "Backend",
    task_assignees: "Sara Ahmed",
    assigneeAvatar: "",
    task_priority:  "Low",
    task_start_date:"Jun 01, 2026",
    task_end_date:  "Jun 29, 2026",
    project_status: "Assigned",
    status:         "Assigned",
    comments:       0,
    attachments:    1,
    title:    "Build notification system",
    priority: "Low",
    deadline: "Jun 29, 2026",
    assigneeName: "Sara Ahmed",
    project: "Mobile Banking App",
  },
  {
    id: "9",
    task:           "Create course enrollment flow",
    projectName:    "Learning Management System",
    module:         "Frontend",
    task_assignees: "Sara Ahmed",
    assigneeAvatar: "",
    task_priority:  "Low",
    task_start_date:"May 10, 2026",
    task_end_date:  "Jun 29, 2026",
    project_status: "New",
    status:         "New",
    comments:       2,
    attachments:    4,
    title:    "Create course enrollment flow",
    priority: "Low",
    deadline: "Jun 29, 2026",
    assigneeName: "Sara Ahmed",
    project: "Learning Management System",
  },
  {
    id: "10",
    task:           "API load testing",
    projectName:    "E-Commerce Platform",
    module:         "QA",
    task_assignees: "Sara Ahmed",
    assigneeAvatar: "",
    task_priority:  "Medium",
    task_start_date:"Jun 03, 2026",
    task_end_date:  "Jun 29, 2026",
    project_status: "New",
    status:         "New",
    comments:       0,
    attachments:    0,
    title:    "API load testing",
    priority: "Medium",
    deadline: "Jun 29, 2026",
    assigneeName: "Sara Ahmed",
    project: "E-Commerce Platform",
  },
  {
    id: "11",
    task:           "Create UI Dashboard",
    projectName:    "Learning Management System",
    module:         "Frontend",
    task_assignees: "Sara Ahmed",
    assigneeAvatar: "",
    task_priority:  "Low",
    task_start_date:"Feb 20, 2026",
    task_end_date:  "Mar 10, 2026",
    project_status: "New",
    status:         "New",
    comments:       0,
    attachments:    5,
    title:    "Create UI Dashboard",
    priority: "Low",
    deadline: "Mar 10, 2026",
    assigneeName: "Sara Ahmed",
    project: "Learning Management System",
  },
  {
    id: "12",
    task:           "Create UI Dashboard",
    projectName:    "Learning Management System",
    module:         "Frontend",
    task_assignees: "Sara Ahmed",
    assigneeAvatar: "",
    task_priority:  "Medium",
    task_start_date:"Feb 22, 2026",
    task_end_date:  "Mar 10, 2026",
    project_status: "Assigned",
    status:         "Assigned",
    comments:       0,
    attachments:    5,
    title:    "Create UI Dashboard",
    priority: "Medium",
    deadline: "Mar 10, 2026",
    assigneeName: "Sara Ahmed",
    project: "Learning Management System",
  },
  {
    id: "13",
    task:           "Create UI Dashboard",
    projectName:    "Learning Management System",
    module:         "Frontend",
    task_assignees: "Sara Ahmed",
    assigneeAvatar: "",
    task_priority:  "Medium",
    task_start_date:"Feb 25, 2026",
    task_end_date:  "Mar 10, 2026",
    project_status: "In Progress",
    status:         "In Progress",
    comments:       0,
    attachments:    5,
    title:    "Create UI Dashboard",
    priority: "Medium",
    deadline: "Mar 10, 2026",
    assigneeName: "Sara Ahmed",
    project: "Learning Management System",
  },
  {
    id: "14",
    task:           "Create UI Dashboard",
    projectName:    "Learning Management System",
    module:         "Frontend",
    task_assignees: "Sara Ahmed",
    assigneeAvatar: "",
    task_priority:  "Low",
    task_start_date:"Mar 01, 2026",
    task_end_date:  "Mar 10, 2026",
    project_status: "Under Review",
    status:         "Under Review",
    comments:       0,
    attachments:    5,
    title:    "Create UI Dashboard",
    priority: "Low",
    deadline: "Mar 10, 2026",
    assigneeName: "Sara Ahmed",
    project: "Learning Management System",
  },
  {
    id: "15",
    task:           "Create UI Dashboard",
    projectName:    "Learning Management System",
    module:         "Frontend",
    task_assignees: "Sara Ahmed",
    assigneeAvatar: "",
    task_priority:  "High",
    task_start_date:"Mar 05, 2026",
    task_end_date:  "Mar 10, 2026",
    project_status: "Completed",
    status:         "Completed",
    comments:       0,
    attachments:    5,
    title:    "Create UI Dashboard",
    priority: "High",
    deadline: "Mar 10, 2026",
    assigneeName: "Sara Ahmed",
    project: "Learning Management System",
  },
];