// src/utils/exportAttendancePdf.js — 
// Generates a PDF of the current attendance summary table using jsPDF + autotable.

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const BRAND_PINK = [170, 36, 147];
const DEFAULT_COMPANY_NAME = "Sprintexa";

// ── Fetch a remote image (e.g. Cloudinary logo URL) and convert to a
// base64 data URL — jsPDF's addImage() needs raw image data, not a URL.
// Same helper as reportPdfExport.js — kept local here since this file
// doesn't import from that module. ──────────────────────────────────────
async function loadImageAsDataUrl(url) {
  try {
    const res = await fetch(url, { mode: "cors" });
    if (!res.ok) throw new Error("Logo fetch failed");
    const blob = await res.blob();
    return await new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload  = () => resolve(reader.result);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch (err) {
    console.error("Failed to load company logo for PDF:", err.message);
    return null;
  }
}

function loadImageElement(src) {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload  = () => resolve(img);
    img.onerror = reject;
    img.src = src;
  });
}

/**
 * Export attendance summary rows to a downloadable PDF.
 * @param {Array} records - filtered summary rows currently shown in the table
 * @param {Object} meta - optional { title, generatedBy, logoUrl, companyName }
 *
 * NOTE: now async — awaits the company logo fetch/conversion before drawing
 * the header. Callers must `await exportAttendancePdf(...)`.
 */
export const exportAttendancePdf = async (records = [], meta = {}) => {
  const doc = new jsPDF({ orientation: "landscape", unit: "pt", format: "a4" });

  const title       = meta.title || "Attendance Records Report";
  const companyName = meta.companyName?.trim() || DEFAULT_COMPANY_NAME;
  const generatedOn = new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });

  // ── Light header band — neutral, works with any logo color ──────────────
  doc.setFillColor(248, 248, 250);
  doc.rect(0, 0, doc.internal.pageSize.getWidth(), 80, "F");
  doc.setDrawColor(...BRAND_PINK);
  doc.setLineWidth(0.75);
  doc.line(0, 80, doc.internal.pageSize.getWidth(), 80);

  let textStartX = 40;
  let logoBottom  = 0;

  if (meta.logoUrl) {
    const dataUrl = await loadImageAsDataUrl(meta.logoUrl);
    const mime = dataUrl?.match(/data:image\/([a-zA-Z0-9+.-]+);/)?.[1]?.toLowerCase();

    if (dataUrl && mime && !mime.includes("svg")) {
      try {
        const imgEl = await loadImageElement(dataUrl);
        const maxHeight = 32; // pt — fits comfortably in the 80pt header band
        const ratio  = imgEl.naturalWidth / imgEl.naturalHeight || 1;
        const height = maxHeight;
        const width  = height * ratio;
        const format = mime.includes("png") ? "PNG" : mime.includes("webp") ? "WEBP" : "JPEG";

        doc.addImage(dataUrl, format, 40, 16, width, height);
        textStartX = 40 + width + 14;
        logoBottom = 16 + height;
      } catch (err) {
        console.error("Failed to render logo in PDF:", err.message);
      }
    }
  }

  // ── Company name — always shown, logo is just an icon/mark ──────────────
  doc.setFontSize(15);
  doc.setFont(undefined, "bold");
  doc.setTextColor(30, 30, 30);
  doc.text(companyName, textStartX, 30);

  // ── Report title — stacked below the company name, brand-colored ────────
  doc.setFontSize(12);
  doc.setFont(undefined, "bold");
  doc.setTextColor(...BRAND_PINK);
  doc.text(title, textStartX, 46);

  doc.setFontSize(9);
  doc.setFont(undefined, "normal");
  doc.setTextColor(120);
  doc.text(`Generated on ${generatedOn}`, textStartX, 60);
  if (meta.generatedBy) {
    doc.text(`Generated by ${meta.generatedBy}`, textStartX, 72);
  }

  // ── Table ───────────────────────────────────────────────────────────────
  const columns = [
    "Emp ID", "Employee", "Department", "Month",
    "Total Present", "Total Absent", "Total Late", "Total Leave", "Total Hours",
  ];

  const rows = records.map((r) => [
    r.empId || "-",
    r.name  || "-",
    r.department || "-",
    r.month || "-",
    r.totalPresent ?? 0,
    r.totalAbsent  ?? 0,
    r.totalLate    ?? 0,
    r.totalLeave   ?? 0,
    r.totalHours   || "-",
  ]);

  autoTable(doc, {
    head: [columns],
    body: rows,
    startY: 96,
    theme: "grid",
    headStyles: {
      fillColor: BRAND_PINK,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9,
    },
    bodyStyles: { fontSize: 9 },
    alternateRowStyles: { fillColor: [250, 245, 250] },
    margin: { left: 40, right: 40 },
  });

  // ── Footer — page numbers + company confidential line + Powered by ──────
  const pageCount = doc.internal.getNumberOfPages();
  const pageWidth  = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);

    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 80, pageHeight - 20);

    doc.text(`${companyName} — Confidential`, 40, pageHeight - 20);

    doc.setFontSize(7);
    doc.setTextColor(190, 190, 190);
    doc.text("Powered by Sprintexa", pageWidth / 2, pageHeight - 20, { align: "center" });
  }

  const fileName = `attendance_records_${new Date().toISOString().split("T")[0]}.pdf`;
  doc.save(fileName);
};