// src/utils/exportAttendancePdf.js — NEW FILE
// Generates a PDF of the current attendance summary table using jsPDF + autotable.


import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

/**
 * Export attendance summary rows to a downloadable PDF.
 * @param {Array} records - filtered summary rows currently shown in the table
 * @param {Object} meta - optional { title, generatedBy }
 */
export const exportAttendancePdf = (records = [], meta = {}) => {
  const doc = new jsPDF({ orientation: "landscape", unit: "pt", format: "a4" });

  const title = meta.title || "Attendance Records Report";
  const generatedOn = new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });

  // ── Header ──────────────────────────────────────────────────────────────
  doc.setFontSize(16);
  doc.setFont(undefined, "bold");
  doc.text(title, 40, 40);

  doc.setFontSize(10);
  doc.setFont(undefined, "normal");
  doc.setTextColor(120);
  doc.text(`Generated on ${generatedOn}`, 40, 58);
  if (meta.generatedBy) {
    doc.text(`Generated by ${meta.generatedBy}`, 40, 72);
  }
  doc.setTextColor(0);

  // ── Table ───────────────────────────────────────────────────────────────
  const columns = [
    "Emp ID", "Employee", "Department", "Month",
    "Total Present", "Total Absent", "Total Late", "Total Leave", "Total Hours",
  ];

  const rows = records.map((r) => [
    r.empId || "-",
    r.name  || "-",
    r.department || "-",
    r.month || "-",
    r.totalPresent ?? 0,
    r.totalAbsent  ?? 0,
    r.totalLate    ?? 0,
    r.totalLeave   ?? 0,
    r.totalHours   || "-",
  ]);

  autoTable(doc, {
    head: [columns],
    body: rows,
    startY: meta.generatedBy ? 90 : 80,
    theme: "grid",
    headStyles: {
      fillColor: [170, 36, 147],   // #AA2493
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9,
    },
    bodyStyles: { fontSize: 9 },
    alternateRowStyles: { fillColor: [250, 245, 250] },
    margin: { left: 40, right: 40 },
  });

  // ── Footer — page numbers ───────────────────────────────────────────────
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Page ${i} of ${pageCount}`,
      doc.internal.pageSize.getWidth() - 80,
      doc.internal.pageSize.getHeight() - 20
    );
  }

  const fileName = `attendance_records_${new Date().toISOString().split("T")[0]}.pdf`;
  doc.save(fileName);
};